all:
  hosts:
  children:
    hadoop_master:
      hosts:
        primary.dev:
          ansible_port: 22
          ansible_host: 172.16.241.100
          as_hostname: primary.dev.vcg.com
          as_gpu: false
          as_hdfs_name_dir: file:///data/hadoop/hdfs/namenode
          as_docker_allowed_rw_mounts: /data5/yarn/data,/data5/yarn/logs
          as_local_dirs: /data5/yarn/data
          as_log_dirs: /data5/yarn/logs
          as_memory_mb: 60960
          as_cpu_vcores: 16
          as_hdfs_data_dir: file:///data/hadoop/hdfs/datanode,file:///data_hadoop_1/hadoop/hdfs/datanode/,file:///data_hadoop_2/hadoop/hdfs/datanode/,file:///data5/hadoop/hdfs/datanode/
#            as_cpu-vcores: 16
#            as_memory-mb: 60960
      vars:
        as_hadoop_master: true
        as_hadoop_slave: true
        as_resourcemanager_address: 172.16.241.100

    hadoop_slave:
      hosts:
        gpu0.dev:
          ansible_port: 22
          ansible_host: 172.16.237.151
          as_hostname: gpu0.dev.vcg.com
          as_gpu: true
          as_local_dirs: /data2/yarn/data
          as_log_dirs: /data2/yarn/logs
          as_cpu_vcores: 16
          as_memory_mb: 60960
          as_hdfs_data_dir: file:///data2/hadoop/hdfs/datanode/,file:///data1/hadoop/hdfs/datanode/
          as_docker_allowed_rw_mounts: /data2/yarn/data,/data2/yarn/logs










      vars:
        as_hadoop_master: false
        as_hadoop_slave: true
        as_resourcemanager_address: 172.16.241.100













