all:
  hosts:
  children:

    machines:
      hosts:
        legion:
          ansible_port: 22
          ansible_host: m1.dev.yufei.com
          as_hostname: m1.dev.yufei.com
      vars:


    vbs_master:
      hosts:
        vb0:
          ansible_port: 22
          ansible_host: vb0.dev.yufei.com
          as_hostname: vb0.dev.yufei.com
          as_gpu: false
          as_hdfs_name_dir: /data/hadoop/hdfs/namenode
          as_docker_allowed_rw_mounts: /data/yarn/data,/data/yarn/logs
          as_local_dirs: /data/yarn/data
          as_log_dirs: /data/yarn/logs
          as_memory_mb: 3300
          as_cpu_vcores: 4
          as_hdfs_data_dir: file:///data/hadoop/hdfs/datanode


      vars:
        as_hadoop_master: true
        as_hadoop_slave: true
        as_resourcemanager_address: vb0.dev.yufei.com
        as_namenode_address: vb0.dev.yufei.com
        as_zk_data_dir: /data/zk_data/
    vbs_slaves:
      hosts:
        vb1:
          ansible_port: 22
          ansible_host: vb1.dev.yufei.com
          as_hostname: vb1.dev.yufei.com
          as_gpu: false
          as_docker_allowed_rw_mounts: /data/yarn/data,/data/yarn/logs
          as_local_dirs: /data/yarn/data
          as_log_dirs: /data/yarn/logs
          as_memory_mb: 2300
          as_cpu_vcores: 4
          as_hdfs_data_dir: file:///data/hadoop/hdfs/datanode


      vars:
        as_hadoop_master: false
        as_hadoop_slave: true
        as_resourcemanager_address: vb0.dev.yufei.com
        as_namenode_address: vb0.dev.yufei.com



    hadoop_master:
      hosts:
        primary.dev:
          ansible_port: 22
          ansible_host: 172.16.104.220
          as_hostname: primary.dev.vcg.com
          as_gpu: false
          as_hdfs_name_dir: file:///data/hadoop/hdfs/namenode
          as_docker_allowed_rw_mounts: /data5/yarn/data,/data5/yarn/logs
          as_local_dirs: /data5/yarn/data,/data_hadoop_2/yarn/data
          as_log_dirs: /data5/yarn/logs
          as_memory_mb: 80960
          as_cpu_vcores: 200
          as_hdfs_data_dir: file:///data_hadoop_2/hadoop/hdfs/datanode/,file:///data5/hadoop/hdfs/datanode/
          as_redis_dbdir: /data5/redis/data/
#            as_cpu-vcores: 16
#            as_memory-mb: 60960

      vars:
        as_hadoop_master: true
        as_hadoop_slave: true
        as_resourcemanager_address: primary.dev.vcg.com
        as_namenode_address: primary.dev.vcg.com

    hadoop_slave:
      hosts:
        gpu0.dev:
          ansible_port: 22
          ansible_host: 172.16.108.176
          as_hostname: gpu0.dev.vcg.com
          as_gpu: true
          as_local_dirs: /data3/yarn/data
          as_log_dirs: /data3/yarn/logs
          as_cpu_vcores: 200
          as_memory_mb: 100960
          as_hdfs_data_dir: file:///data3/hadoop/hdfs/datanode/
          as_docker_allowed_rw_mounts: /data3/yarn/data,/data3/yarn/logs










      vars:
        as_hadoop_master: false
        as_hadoop_slave: true
        as_resourcemanager_address: primary.dev.vcg.com
        as_namenode_address: primary.dev.vcg.com













