---
- hosts: all
  gather_facts: true
  roles:
    - role: comm


      vars:
      tags: comm
    - role: hadoop
      vars:
      tags: hadoop
    - role: kafka
      vars:
      tags: kafka
    - role: zk
      vars:
      tags: zk
    - role: redis
      become: yes
      vars:
      tags: redis
    - role: docker
      become: yes
      vars:
      tags: docker
    - role: conda
      become: yes
      vars:
      tags: conda
    - role: es
      become: yes
      vars:
      tags: es
#    - role: davidwittman.redis
#      become: yes
#      tags: redis







