---
- hosts: all
  gather_facts: true
  roles:
    - role: comm


      vars:
      tags: comm
    - role: hadoop
      vars:
      tags: hadoop
    - role: kafka
      vars:
      tags: kafka
    - role: zk
      vars:
      tags: zk







