---
- name: restart zookeeper
  shell:  bash -l -c '{{zk_home}}bin/bin/zkServer.sh restart'
#  when: as_hadoop_slave
  tags: zk_restart
  async: 30
  poll: 2

- name: start zookeeper
  shell:  bash -l -c '{{zk_home}}bin/zkServer.sh start'
#  when: as_hadoop_slave
  tags: zk_start
  async: 30
  poll: 2


- name: upload zk.tgz to remote machine
  become: yes
  become_user: root
  unarchive:
    src: "{{zk_libary_dir}}"
    dest: "{{remote_zk_dir}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
  tags: zk_setup


- name: zk change foler permission
  become: yes
  become_user: root
  tags: zk_setup
  file:
    path: "{{zk_home}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory



- name: zk data dir
  become: yes
  become_user: root
  tags: zk_setup
  file:
    path: "{{zk_data_dir}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory
- name: zk config files
  template:
    dest: "{{zk_home}}conf/{{item.dest}}"
    src: templates/{{item.src}}
    mode: u=rw,g=r,o=r
    owner: zhaoyufei
    group: hadoop
  become: yes
  become_user: root
  tags: zk_config
  with_items:
        - {src: 'zoo.cfg',dest: 'zoo.cfg'}




