---
- name: restart zookeeper
  shell:  bash -l -c '{{zk_home}}bin/bin/zkServer.sh restart'
#  when: as_hadoop_slave
  tags: zk_restart
  async: 30
  poll: 2

- name: start zookeeper
  shell:  bash -l -c '{{zk_home}}bin/zkServer.sh start'
#  when: as_hadoop_slave
  tags: zk_start
  async: 30
  poll: 2
- name: make sure all related folders present, if present do nothing
  become: yes
  become_user: root
  tags: zk_install
  file:
    path: "{{item}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory
  loop:
    - "{{app_logRootDir}}{{appName}}/"
    - "{{app_dataRootDir}}{{appName}}/"
    - "{{app_confRootDir}}{{appName}}/"
    - "{{app_rootDir}}{{appName}}/"
- name: upload zk.tgz and unzip to  remote machine
  become: yes
  become_user: root
  tags: zk_install
  unarchive:
    src: "{{zk_libary_dir}}"
    dest: "{{app_rootDir}}{{appName}}/"
    extra_opts: [--strip-components=1]
#    creates: "{{app_rootDir}}{{appName}}/"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
#- name: upload zk.tgz to remote machine
#  become: yes
#  become_user: root
#  unarchive:
#    src: "{{zk_libary_dir}}"
#    dest: "{{app_rootDir}}"
#    owner: zhaoyufei
#    group: hadoop
#    mode: u=rwx,g=xr,o=x
#  tags: zk_setup


#- name: zk change foler permission
#  become: yes
#  become_user: root
#  tags: zk_setup
#  file:
#    path: "{{zk_home}}"
#    owner: zhaoyufei
#    group: hadoop
#    mode: u=rwx,g=xr,o=x
#    recurse: yes
#    state: directory



#- name: zk data dir
#  become: yes
#  become_user: root
#  tags: zk_setup
#  file:
#    path: "{{app_dataRootDir}}{{appName}}/"
#    owner: zhaoyufei
#    group: hadoop
#    mode: u=rwx,g=xr,o=x
#    recurse: yes
#    state: directory
- name: zk config files
  template:
    dest: "{{item.dest}}"
    src: templates/{{item.src}}
    mode: u=rw,g=r,o=r
    owner: zhaoyufei
    group: hadoop
  become: yes
  become_user: root
  tags: zk_config
  with_items:
        - {src: 'zoo.cfg',dest: '{{app_confRootDir}}{{appName}}/zoo.cfg'}
        - {src: 'zkEnv.sh',dest: '{{app_rootDir}}{{appName}}/bin/zkEnv.sh'}




