---
# kafka operations


- name: start kafka
  shell:  bash -l -c ' nohup {{kafka_home}}bin/kafka-server-start.sh {{kafka_home}}/config/server.properties &'
#  when: as_hadoop_slave
  tags: kafka_start
  async: 30
  poll: 2

- name: restart kafka
  shell:  bash -l -c '{{kafka_home}}bin/kafka-server-stop.sh {{kafka_home}}/config/server.properties' ; bash -l -c 'nohup {{kafka_home}}bin/kafka-server-start.sh {{kafka_home}}/config/server.properties &'
#  when: as_hadoop_slave
  tags: kafka_restart
  async: 30
  poll: 2

#kafka config


- name: upload kafka.tgz to remote machine
  unarchive:
    src: "{{kafka_libary_dir}}"
    dest: "{{remote_kafka_dir}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
  tags: kafka_setup


- name: kafka change foler permission
  become: yes
  become_user: root
  tags: kafka_setup
  file:
    path: "{{kafka_home}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory



- name: kafka log dir present
  become: yes
  become_user: root
  tags: kafka_setup
  file:
    path: "{{kafka_log_dirs}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory
- name: kafka config files
  template:
    dest: "{{kafka_home}}config/{{item.dest}}"
    src: templates/config/{{item.src}}
    mode: u=rw,g=r,o=r
    owner: zhaoyufei
    group: hadoop
  become: yes
  become_user: root
  tags: kafka_config
  with_items:
        - {src: 'server.properties',dest: 'server.properties'}
        - {src: 'log4j.properties',dest: 'log4j.properties'}




#
#
#
#
#
#
#
#









