---
# kafka operations


#- name: start kafka
#  shell:  bash -l -c ' nohup {{kafka_home}}bin/kafka-server-start.sh {{kafka_home}}/config/server.properties &'
##  when: as_hadoop_slave
#  tags: kafka_start
#  async: 30
#  poll: 2
#
#- name: restart kafka
#  shell:  bash -l -c '{{kafka_home}}bin/kafka-server-stop.sh {{kafka_home}}/config/server.properties' ; bash -l -c 'nohup {{kafka_home}}bin/kafka-server-start.sh {{kafka_home}}/config/server.properties &'
##  when: as_hadoop_slave
#  tags: kafka_restart
#  async: 30
#  poll: 2

#- name: start
#  -
#kafka config
- name: check if jdk installed
  tags: kafka_install
  shell: command -v java
  register: check_java
  ignore_errors: True
  changed_when: False
#- name: kafka install debug
#  tags: kafka_install
#
#
#  debug:
#    msg: "{{check_java}}"
- name: if not install jdk, will exit
  tags: kafka_install
  block:
    - debug:
        msg: please install jdk before kafka, will exit!
    - meta: end_play
  when: check_java.rc > 0






- name: jdk check block
  tags: kafka_install
  block:
    - name:
      debug:
        msg: please install jdk before kafka
    - name:
      meta: end_play
  when: check_java.rc > 0






- name: make sure all related folders present, if present do nothing
  become: yes
  become_user: root
  tags: kafka_install
  file:
    path: "{{item}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
    recurse: yes
    state: directory
  loop:
    - "{{kafka_logRootDir}}{{appName}}/"
    - "{{kafka_dataRootDir}}{{appName}}/"
    - "{{kafka_confRootDir}}{{appName}}/"
    - "{{app_rootDir}}{{appName}}/"


- name: upload kafka.tgz and unzip to  remote machine
  become: yes
  become_user: root
  tags: kafka_install
  unarchive:
    src: "{{kafka_libary_dir}}"
    dest: "{{app_rootDir}}{{appName}}/"
    extra_opts: [--strip-components=1]
    creates: "{{app_rootDir}}{{appName}}/"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x
- name: copy orginal config files to conf folder
  become: yes
  become_user: root
  tags: kafka_install
  copy:
    src: templates/config/
    dest: "{{kafka_confRootDir}}{{appName}}"
    owner: zhaoyufei
    group: hadoop
    mode: u=rwx,g=xr,o=x






- name: kafka config files
  template:
    dest: "{{kafka_confRootDir}}{{appName}}/{{item.dest}}"
    src: templates/config/{{item.src}}
    mode: u=rw,g=r,o=r
    owner: zhaoyufei
    group: hadoop
  become: yes
  become_user: root
  tags: kafka_config
  with_items:
        - {src: 'server.properties',dest: 'server.properties'}
        - {src: 'log4j.properties',dest: 'log4j.properties'}














