- name: Update apt cache
  tags: docker_install
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  tags: docker_install
  apt: upgrade=dist

- name: Install dependencies
  tags: docker_install
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent

- name: Add an apt signing key for Docker
  tags: docker_install
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  tags: docker_install
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  tags: docker_install
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add user to docker group
  tags: docker_install
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Download docker-compose {{ docker_compose_version }}
  tags: docker_install
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: '+x'

- name: Check docker-compose exists
  tags: docker_install
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  tags: docker_install
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists
